In [16]:
class student :
    def __init__(self,name , age):
        self.name = name
        self.age = age

    def __str__(self):
       return f"my name is {self.name}, my age is {self.age}"
    def __repr__(self):
        return f"my name is {self.name}, my age is {self.age}"
        

In [17]:
s1 = student("JOY",21)
s1

my name is JOY, my age is 21

In [19]:
pip install nympy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement nympy (from versions: none)
ERROR: No matching distribution found for nympy

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
import numpy as np


In [27]:
s= np.array(5)
print(s)
v= np.array(x)
print(v)
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m)

5
[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec = np.array([1,2,3,4])
mat = vec.reshape

In [29]:
def array_reshape(arr:list,rows:int,cols:int):
    try:
      arr= np.array(arr)
      return arr.reshape(rows , cols)
    except (TypeError, ValueError) as e:
       raise ValueError(f"invalid reshape operation:{e}")

In [31]:
vec = [ 1,2,3,4,5,6,]
array_reshape(vec, 2,3)

array([[1, 2, 3],
       [4, 5, 6]])